### ISSUE TITLE
How I can create my first query ?

### ISSUE THREAD

**Issue by salemkode** [memocash/index#31]
I am start using memecash/index in my server and I do can get list of port I need to use, because I need run full client in my server
![image](https://github.com/memocash/index/assets/58360393/d2291e57-5315-4f36-8fa3-aab0bb2eb9e2)

I think I need use another port

**Comment by jchavannes** [comment]
@salemkode here is a query you can try. You have the right port.

```
curl -H 'Content-Type: application/json' -X POST -d '{"query": "query { blocks { hash timestamp height size tx_count }}"}' http://localhost:26770/graphql
```

**Comment by jchavannes** [comment]
@salemkode do you need any more help with this?
